# Generated by Django 3.1.7 on 2021-05-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum', models.CharField(max_length=200)),
                ('ders', models.CharField(max_length=200)),
                ('sinav_tipi', models.CharField(max_length=200)),
                ('tc', models.BigIntegerField(max_length=11)),
            ],
        ),
    ]
