# Generated by Django 3.1.7 on 2021-05-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinav',
            name='tc',
            field=models.BigIntegerField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='sinav',
            unique_together={('ders', 'sinav_tipi', 'tc')},
        ),
        migrations.RemoveField(
            model_name='sinav',
            name='id',
        ),
    ]
