# Generated by Django 3.1.7 on 2021-05-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210511_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinav',
            name='kagit',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
